name: Build and run tests

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build_and_package:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: npm install

      - name: Echo
        run: |
          echo "All vars context:"
          echo "${{ toJSON(vars) }}"
          echo "All secrets context:"
          echo "${{ toJSON(secrets) }}"

      - name: Run testsuite
        env:
          VITE_CLERK_PUBLISHABLE_KEY: ${{ vars.VITE_CLERK_PUBLISHABLE_KEY }}
        run: npm test